### ISSUE TITLE
Connecting the Jetson TX2

### ISSUE THREAD

**Issue by mandelyoni** [prgumd/GapFlyt#3]
Hi,

Where can I find the instructions on how to connect the Jetson to the Bebop?

Thank you

**Comment by NitinJSanket** [comment]
We haven't added the instructions for connecting the Jetson to the Bebop yet. We'll do it by Wednesday (31st Oct).

**Comment by mandelyoni** [comment]
Great, thank you

**Comment by chahatdeep** [comment]
Hi @mandelyoni 
Sorry for the delay. The wiki is now updated with [hardware instructions](https://github.com/prgumd/Parrot-Bebop2-Setup) and [TX2 Ubuntu 16.04-L4T](https://github.com/chahatdeep/ubuntu-for-robotics/tree/master/Nvidia-TX2-JetPack-setup) setup.

**Comment by mandelyoni** [comment]
Thank you very much !
